### PR TITLE
fedora's kernel and updated readme

### PR DESCRIPTION
**Pull request by t3d**

### CODE REVIEW

**Comment by goldmann** [comment]
I pulled the README fix, thanks!

But I'm not sure about the kernel changes. At the time of building we don't know with what hardware profile the image will be launched. See first note for hardware section: http://boxgrinder.org/tutorials/appliance-definition/#hardware. This means that an image with selected 512 MB of RAM in appliance definition file could be run later for example on VMware with 8 GB of RAM. The save setting here is using kernel-PAE package always.

Said that, I'll pull your change because someone who's building the appliance should really know what are the requirements for it.

This needs testing (especially on EC2).

Thank you!

**Comment by t3d** [comment]
As for the PAE, I also have serious doubts, but rather related to loss of NX bit. Moreover, the situation is even more complicated as when you don't explicitly set the allocated amount of RAM, boxgrinder itself assigns 256MB by default, which in my scenario is the elimination of PAE.

I think that the ultimate solution would be to have an additional setting like "use-PAE" on / off  in the hardware section. 
Well, to be honest, it also would be convenient if someone could set architecture there, because using "setarch" is a rather dirty hack, and could be unwittingly forgotten, especially if you use the same aplliance definition on both 64, and 32-bit hosts.

My change was due to the fact that I need non-PAE kernel, and my attempts to add the "kernel" to the packages did not provide the deserved outcome (Now I know why: D).

**Comment by goldmann** [comment]
I would still like to have an English comments because other people may profit from it.

Definition format was established to be architecture independent. This was a goal of the design. Your suggestion, that we should be able to choose PAE or non-PAE kernels is valid, I need to think about it. Once JIRA wakes up, I'll create an issue to track this.

As a side note - I checked EC2 builds and it requires PAE kernel to run for 32 bit AMIs. This needs to be fixed shortly.

**Comment by goldmann** [comment]
Created https://issues.jboss.org/browse/BGBUILD-190

**Comment by t3d** [comment]
Thanks! This solves the issue, and makes boxgrinder even more flexible.

**Pull request closed without merging**
