### PR TITLE
using guestfs_helper to wrap the kernel install

### PR DESCRIPTION
**Pull request by jgehtland**
I've been trying to build a 32bit AMI from the 64bit meta-appliance.  The problem is that the ec2-plugin ignores that the user has used "setarch i686" to run boxgrinder-build.  This patch simply uses the guestfs_helper to launch the yum kernel-xen install instead of the direct guestfs.

### CODE REVIEW

**Comment by goldmann** [comment]
I'll check the tests and if they pass then I'll merge your commit, thanks!

**Comment by goldmann** [comment]
I pulled the change and fixed the test, thanks!

**Comment by jgehtland** [comment]
Rock on, and thanks for all the hard work.  I'm about to go spelunking
on another task, but maybe you already have an answer: I need to set
the "name" attribute of an uploaded AMI so I can disambiguate in the
AWS console.  I'll happily add this capability if it does not already
exist, but if it does, I won't. Thoughts?

On Mon, Nov 7, 2011 at 11:08 AM, Marek Goldmann
reply@reply.github.com
wrote:

> I pulled the change and fixed the test, thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/boxgrinder/boxgrinder-build/pull/3#issuecomment-2655344

## 

Justin Gehtland |  Relevance, Inc.
919.824.5409 | @jgehtland

**Comment by goldmann** [comment]
The name is set to appliance name with additional info like version, release, arch, OS name and OS version, but feel free to create new ticket so we can discuss it and track the work: https://issues.jboss.org/browse/BGBUILD

**Pull request merged**
